<?php
/**
 * AssetRev config.php
 *
 * This file exists only as a template for the AssetRev settings.
 * It does nothing on its own.
 *
 * Don't edit this file, instead copy it to 'craft/config' as 'assetrev.php'
 * and make your changes there to override default settings.
 *
 * Once copied to 'craft/config', this file will be multi-environment aware as
 * well, so you can have different settings groups for each environment, just as
 * you do for 'general.php'
 */

return array(

    // The path to your asset manifest; most likely generated by a task runner
    // such as Gulp or Grunt. The path will be relative to your Craft base
    // directory, unless you supply an absolute path.

    'manifestPath' => 'resources/assets/assets.json',

    // The path where your built asset files can be found. Required for query
    // string creation. Again, this is relative to your Craft base directory,
    // unless you supply an absolute path.

    'assetsBasePath' => '',

    // A prefix to apply to your asset filenames when they are output. You would
    // likely want to set this if the paths in your manifest file are going to
    // be different to the final intended asset URL.

    'assetUrlPrefix' => null,

);
